---
title: "annewill"
author: "dh118, ss597"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(igraph)
library(tidygraph)
library(manynet)
library(tidyverse)
```

# Netzwerk einlesen

```{r Netzwerk einlesen}

el <- read.csv("https://raw.githubusercontent.com/davi181nicht187/pretest/refs/heads/main/Edgelist%20Pretest%20-%20SNA%20Gruppe1.csv", header=T, as.is=T, sep = ",")

nl <- read.csv("https://raw.githubusercontent.com/davi181nicht187/pretest/refs/heads/main/Nodelist%20Pretest%20-%20SNA%20Gruppe_1.csv", header=T, as.is=T, sep = ",")

el

nl
nl$id <- as.integer(as.factor(nl$id))
el$from <- as.integer(as.factor(el$from))
el$to <- as.integer(as.factor(el$to))

el

nl
```


# Netzwerk erstellen

```{r Netzwerk erstellen}

pre <- tbl_graph(nodes = nl, edges = el, directed = FALSE)

pre

```


```{r}
V(pre)$color <- case_when(
V(pre)$typ == 3 ~ "yellow",
V(pre)$typ == 1 ~ "red",
V(pre)$typ == 2 ~ "lightblue"
)
```


```{r}
plot(pre,
   layout=layout_nicely,
  main="2. Pretest (12.3.)"
  )
```

# codebuch und Zeitaufwand
```{r}
"https://github.com/davi181nicht187/pretest/blob/main/Codebuch.md" #codebuch

zSNA1 <- read.csv("https://raw.githubusercontent.com/davi181nicht187/pretest/refs/heads/main/Zeitaufwand%20Gruppe1%20-%20Tabellenblatt1.csv", header=T, as.is=T, sep = ",") #Zeitaufwand

zSNA1
```


